# 插件管理器
[[plugins]]
repo = 'Shougo/dein.vim'

# A solid language pack for Vim.
# (syntax, indent, autoload, ftplugin)
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['markdown', 'tsx', 'typescript', 'csv', 'rust']
'''

# Yet Another TypeScript Syntax
[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
#
# # Folding setting for diff.
# [[plugins]]
# repo = 'thinca/vim-ft-diff_fold'
#
# # Folding setting for help.
# [[plugins]]
# repo = 'thinca/vim-ft-help_fold'
#
# # Text Formatting Plugin
# [[plugins]]
# repo = 'vim-jp/autofmt'
#
# [[plugins]]
# repo = 'kana/vim-textobj-user'
#
# [[plugins]]
# repo = 'kana/vim-operator-user'

# markdown
[[plugins]]
repo = 'rcmdnk/vim-markdown'

# vim 测试框架
[[plugins]]
repo = 'thinca/vim-themis'

## CTRLP matcher
# [[plugins]]
# repo = 'nixprime/cpsm'
# build = 'sh -c "PY3=ON ./install.sh"'

## ASM
# [[plugins]]
# repo = 'Shirk/vim-gas'

# [[plugins]]
# repo = 'chrisbra/vim-zsh'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'

## themes
[[plugins]]
repo = 'mhinz/vim-janah'

[[plugins]]
repo = 'challenger-deep-theme/vim'

[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'sickill/vim-monokai'

[[plugins]]
repo = 'drewtempelmeyer/palenight.vim'

[[plugins]]
repo = 'ayu-theme/ayu-vim'

# [[plugins]]
# repo = 'tbodt/deoplete-tabnine'
# build = './install.sh'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

