[[plugins]]
repo = 'Shougo/neoyank.vim'
on_event = 'TextYankPost'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = 'denite.nvim'
hook_add = '''
  nnoremap <silent> [Window]e :<C-u>Denite junkfile:new junkfile<CR>
'''

[[plugins]]
repo = 'chemzqm/denite-git'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Jagua/vim-denite-ghq'
on_source = 'denite.nvim'

[[plugins]]
repo = 'raghur/fruzzy'
on_source = ['denite.nvim']
hook_source = 'let g:fruzzy#sortonempty = 0'
hook_post_update = 'call fruzzy#install()'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = '''
  execute 'source' vimrc#expand('rc/plugin/denite.vim')
'''
hook_add = '''
  nnoremap <silent> ;r
        \ :<C-u>Denite -buffer-name=register
        \ register neoyank<CR>
  xnoremap <silent> ;r
        \ :<C-u>Denite -default-action=replace -buffer-name=register
        \ register neoyank<CR>

  nnoremap <silent> [Window]<Space>
        \ :<C-u>Denite -split=floating file/rec:'~/.config/nvim/config' 
		\ file/rec:'~/.config/nvim/rc'<CR>
  "nnoremap <expr> / line('$') > 10000 ? '/' :
  "\ ":\<C-u>Denite -buffer-name=search -start-filter line\<CR>"
  "nnoremap <expr> n line('$') > 10000 ? 'n' :
  "\ ":\<C-u>Denite -buffer-name=search -resume -refresh -no-start-filter\<CR>"
  "nnoremap <expr> * line('$') > 10000 ? '*' :
  "\ ":\<C-u>DeniteCursorWord -buffer-name=search line\<CR>"
  nnoremap <silent> [Window]s :<C-u>Denite -split=vertical buffer<CR>
  nnoremap <silent> [Window]p :<C-u>Denite -split=no file/point file/old
        \ -sorters=sorter/rank
        \ `finddir('.git', ';') != '' ? 'file/rec/git' : 'file/rec'`
        \ file file:new<CR>

  nnoremap <silent><expr> tt  &filetype == 'help' ?  "g\<C-]>" :
        \ ":\<C-u>DeniteCursorWord -buffer-name=tag -immediately
        \  tag:include\<CR>"
  nnoremap <silent><expr> tp  &filetype == 'help' ?
        \ ":\<C-u>pop\<CR>" : ":\<C-u>Denite jump\<CR>"

  nnoremap <silent> [Window]n :<C-u>Denite dein<CR>
  nnoremap <silent> [Window]g :<C-u>Denite ghq -default-action=cd<CR>
  nnoremap <silent> ;f :<C-u>Denite -split=horizontal -buffer-name=search
        \ -no-empty grep<CR>
  nnoremap <silent> ft :<C-u>Denite -split=floating filetype<CR>
  nnoremap <silent> <C-t> :<C-u>Denite -buffer-name=deol -split=floating
  \ -cursor-pos=`tabpagenr()-1` deol:zsh<CR>
  "nnoremap <silent> <C-k> :<C-u>Denite change jump<CR>
  nnoremap <silent> <C-h> :<C-u>DeniteCursorWord help<CR>

  nnoremap <silent> [Space]gs :<C-u>Denite -split=no gitstatus<CR>
  nnoremap <silent> [Space]gl :<C-u>Denite -split=no gitlog:all<CR>
  nnoremap <silent> ;;
        \ :<C-u>Denite command command_history<CR>
'''

[plugins.ftplugin]
denite = '''
  " Define mappings
  nnoremap <silent><buffer><expr> <CR>  denite#do_map('do_action')
  nnoremap <silent><buffer><expr> o     denite#do_map('do_action', 'open')
  nnoremap <silent><buffer><expr> a     denite#do_map('do_action', 'add')
  nnoremap <silent><buffer><expr> d     denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> r     denite#do_map('do_action', 'reset')
  nnoremap <silent><buffer><expr> c     denite#do_map('do_action', 'commit')
  nnoremap <silent><buffer><expr> p     denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q     denite#do_map('quit')
  nnoremap <silent><buffer><expr> i     denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space> denite#do_map('toggle_select').'j'
'''



